# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlshortener',
            name='shortcode',
            field=models.CharField(default='defaultshortcode', max_length=20),
            preserve_default=False,
        ),
    ]
