# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_urlshortener_shortcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortener',
            name='shortcode',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
